version: '3.8'

services:
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6379
    networks:
      - poc_network

  session_control:
    image: "adizele/poc-2:latest"
    depends_on:
      - redis
    restart: always
    networks:
      - poc_network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3000  # Adaptez le port en fonction de l'application
      - 5900
    #command: ["node", "server.js"]

networks:
  poc_network:
    driver: bridge
